--Drops current tables in DB and re-adds tables over again on Server restart

DROP TABLE IF EXISTS 
    status,
    users, 
    projects,
    li_profile;

--Please keep the order of the CREATE TABLE inserts the same

CREATE TABLE status (
    id SERIAL PRIMARY KEY,
    status TEXT
 );

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username TEXT unique,
    first_name TEXT,
    last_name TEXT,
    email TEXT unique, 
    password TEXT,
    company TEXT,
    status_id int references status(id)
 );

CREATE TABLE projects (
    id SERIAL PRIMARY KEY,
    user_id int references users(id),
    name TEXT,
    date TEXT
);

CREATE TABLE li_profile (
    id SERIAL PRIMARY KEY,
    name TEXT,
    summary TEXT,
    company TEXT,
    experience TEXT,
    years TEXT,
    past_company TEXT,
    past_experience TEXT,
    past_years TEXT,
    skill1 TEXT,
    skill2 TEXT,
    skill3 TEXT,
    degree TEXT,
    school TEXT,
    school_years TEXT,
    avatar TEXT,
    profile TEXT,
    project_id int references projects(id),
    swiped_right BOOLEAN,
    swiped_left BOOLEAN,
    status_id int references status(id)
);



-----------Start of Test user info---------------

--Status Table

INSERT INTO status ( status )
VALUES
    ('active'),
    ('inactive')

;
--User Table

INSERT INTO users ( username, first_name, last_name, email, password, company, status_id )
VALUES
    ('Rec0', 'Chad', 'Zuniga', 'czuniga@thumbtack.com', 'password1', 'Thumbtack', 1),
    ('Rec1', 'Cam', 'Crump', 'ccrump@thumbtack.com', 'password1', 'Thumbtack', 1),
    ('Rec2', 'James', 'Adams', 'jadams@thumbtack.com', 'password1', 'Thumbtack', 1),
    ('Rec3', 'Jeremy', 'Oslund', 'joslund@thumbtack.com', 'password1', 'Thumbtack', 1),
    ('Rec4', 'Jacob', 'Gibson', 'jgibson@thumbtack.com', 'password1', 'Thumbtack', 1),
    ('Rec5', 'Sarah', 'Paulson', 'spaulson@thumbtack.com', 'password1', 'Thumbtack', 1),
    ('Rec6', 'Steven', 'Pollock', 'spollock@thumbtack.com', 'password1', 'Thumbtack', 1),
    ('Rec7', 'Noah', 'Lee', 'nlee@thumbtack.com', 'password1', 'Thumbtack', 1),
    ('Rec8', 'Sabrina', 'Parry', 'sparry@thumbtack.com', 'password1', 'Thumbtack', 1),
    ('Rec9', 'Joe', 'Mero', 'jmero@thumbtack.com', 'password1', 'Thumbtack', 1)


;

--Projects

INSERT INTO projects (user_id, name, date)
VALUES
    (1, 'Full Stack Software Engineers', '4/18/2018'),
    (1, 'Front End Software Engineers', '4/20/2018'),
    (1, 'Back End Software Engineers', '4/28/2018'),
    (1, 'Site Reliablility Engineers', '5/1/2018'),
    (1, 'Data Scientists', '5/1/2018')

;

--LinkedIn Profiles

INSERT INTO li_profile ( name, summary, company, experience, years, past_company, past_experience, past_years, skill1, skill2, skill3, degree, school, school_years, avatar, profile, project_id, swiped_right, swiped_left, status_id )
VALUES
    ('Chad Zuniga', 'Aspiring full stack developer currently recruiting Software Engineers for Thumbtack', 'Sr. Techincal Sourcer @ Thumbtack', 'Recruiting Software Engineers', '2015-Present', 'Student Developer @ Dev Mountain', 'Student Developer', '2017-2018', 'Node.js', 'PostgreSQL', 'React', 'BA Business Management', 'Kansas Welseyan University', '2011-2013', 'https://www.goaltos.com/wp-content/uploads/sites/4559/2018/01/avatar-1577909_960_720.png', 'www.linkedin.com/in/chad-zuniga-425735bb/', 1, FALSE, FALSE, 1),
    ('Austin Wright', 'I am a full-stack web developer with a passion for family, music, computers, technology, religion, and all things outdoors. I got into web development to be more immersed in the tech field where I can help create websites and applications to make life better for people around the world.', 'Full Stack Web Developer @ Dev Mountain', 'Redesigned and built Lahnas Chocolates website', '2017-2018', 'Full Stack Web Developer @ Dev Mountain', 'Served as a member of the group who designed and built Planappus.', '2017-2018', 'JavaScript', 'React.js', 'Node.js', 'AS General Studies', 'Salt Lake Community College', '2013-2018', 'https://media.licdn.com/dms/image/C4E03AQFqGpa_shoH6w/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=KkK5a3D7P03cdS3QqtO9pBM3adbsoQm8a7KylAjyaas', 'www.linkedin.com/in/in/theaustinwright/', 1, FALSE, FALSE, 1),
    ('Landon Johnson', 'Bright, talented and ambitious IT support technician with strong technical background, possessing self-discipline and the ability to work with minimum supervision.', 'Graphic Design Intern @ More Good Foundation', 'Orem, UT', '2017-2017', 'Computer Technician @ PcCareSupport', 'Perform inbound and outbound calls from existing and new clients.', '2013-2014', 'Graphic Design', 'Illustrator', 'Photoshop', 'Fullstack Javascript Development', 'DevMountain', '2017-2018', 'https://media.licdn.com/dms/image/C5603AQG3JSoqovpsjQ/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=UNxFDWSO4skDctfqK8fbIY_Tl2WaP5e-9h_wMhapQ1k', 'www.linkedin.com/in/landonwjohnson/', 1, FALSE, FALSE, 1),
    ('Greg Roberts', 'Front-end Web Developer', 'Web Developer @ BambooHR', 'Web Developer', '2015-Present', 'Front-end Web Developer @ InsideSales.com', 'Building responsive web pages, micro-sites, and web apps for the InsideSales.com marketing team.', '2013-2015', 'CSS', 'HTML 5', 'AngularJS', 'Web Development', 'Dev Mountain', '2014-2014', 'https://media.licdn.com/dms/image/C5603AQH3FpC-HgVq1A/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=RlqbwjdmqBAlYS3ZWbXIJjDHu2YAvr2l-VpGDAyGBHo', 'www.linkedin.com/in/gregorystephenroberts/', 1, FALSE, FALSE, 1),
    ('Samuel Skeen', 'I have a passion for programming, a veneration for web development and design. I can program anywhere JavaScript can run', 'Frontend Developer @ Red Pepper Software', 'Pleasant Grove, Utah', '2018-Present', 'After-hours Web Mentor @ Dev Mountain', 'Help students learn JavaScript, React, Node, and Postgres in a 16-week, intensive bootcamp course.', '2017-Present', 'JavaScript', 'CSS', 'JQuery', 'Web Development Certification', 'Dev Mountain', '2015-2015', 'https://media.licdn.com/dms/image/C5603AQEJ6I9Uvs8N3Q/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=cKwfO12yskv6eYlbyFzeSqquVYElOOX6VIEcT0oE75A', 'www.linkedin.com/in/cwadrupldijjit/', 1, FALSE, FALSE, 1),
    ('Paul Olsen', 'Fought multiple ventilation fires on a 500 foot US Naval Vessel. Obsessed with the intersection between people and technology. Chose not to climb Mt. Fuji.', 'Student Success Manager @ DevMountain', 'Enabling the next wave of Creators and Developers!', '2017-Present', 'Technical Sourcer/Recruiter @ Thumbtack', 'Sourcing Engineering candidates through LinkedIn, Github, Slack, Reddit, Search ', '2015-2017', 'SaaS', 'Android', 'iOS', 'Center for Information Dominance Unit', 'US Navy', '2008-2012', 'https://media.licdn.com/dms/image/C5603AQEVub1bk84TTA/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=3I-oU16izLsSa5eLgObAKuxTwsA53dWcC1OIBTYu4kU', 'www.linkedin.com/in/paulolsen1337/', 1, FALSE, FALSE, 1),
    ('Jon Myrick', 'In my years of professional software development, I have had extensive experience coding and working in teams where communication is essential to success. I know how to find answers and get the job done right the first time.', 'Full Stack Javascript Developer @ Vivint Solar', 'API (REST,SOAP) Front Javascript(React), Backend Javascript (Node.js), MongoDB, AWS, Unit Testing', '2017-Present', 'Instructor @ Dev Mountain', 'Instructor', '2016-Present', 'JavaScript', 'Node.js', 'React.js', 'BA Computer Science', 'Brigham Young University', '2015', 'https://media.licdn.com/dms/image/C5103AQHJmsWsjdcT1Q/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=ikv34rv8qn9Lv4LFhhyLxDGenLg_Cwd4vGGXT13soas', 'www.linkedin.com/in/jonmyrick/', 1, FALSE, FALSE, 1),
    ('Joshua Smith', 'I love programming, solving problems, and creating cool stuff. Im crazy about react and javascript (ES6), but thats not all I can do. I currently work two jobs with two different stacks.', 'Software Developer @ Alder Holdings', 'We build and maintain alders customer management and sales tracking software.', '2017-Present', 'Software Instructor @ Dev Mountain', 'At DevMountain we teach by doing. We build projects together, we discuss and demonstrate programing concepts together, and we show practical real world applications for those concepts.', '2017-Present', 'Web Development', 'Front-end Development', 'Node.js', 'BS Sports and Exercise', 'Utah Valley University', '2016-2020', 'https://media.licdn.com/dms/image/C4E03AQHZJmUdm-_-CQ/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=_RQVJzKMF-ZhVmqzamp1M9ouVe2y-K7S-TBFlHsDYoE', 'www.linkedin.com/in/joshua-smith-66a90888/', 1, FALSE, FALSE, 1),
    ('Brian Rogers', 'Strong ability to be versatile with skillset that includes both PHP development and DevOps experience - Highly motivated in both personal and professional endeavors', 'Freelance Software Consultant @ Lucky Dev Shop', 'I am a full-time freelance software developer and consultant. I can assist you, or a team at your company, with a myriad of tasks.', '2017-Present', 'Senior Director of Technology @ ControlPad', 'I was the principle architect for the core product offered, responsible for deciding project guidelines, workflow, and standardization for a team of front-end and back-end developers.', '2015-2017', 'PHP', 'JavaScript', 'Web dev', 'BS Computer Science', 'Southern Utah University', '2009-2011', 'https://media.licdn.com/dms/image/C5603AQE-eWN8HIZhEw/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=P4QNX39FUC_x63Gzs58i7SA1ive5HVNJbwAOCEGZswA', 'www.linkedin.com/in/captbrogers/', 1, FALSE, FALSE, 1),
    ('Timothy Johnson', 'Senior Software Engineer at Silicon Mountain Technologies', 'Sr. Software Engineer @ Silicon Mountain Technologies', 'Westminster, Colorado', '2013-Present', 'Senior Web Developer @ Summit Web Dev', 'Thornton, Colorado', '2010-Present', 'E-commerce', 'Web Development', 'CMS', 'BS Computer Science', 'Colorado State University', '1999-2003', 'https://media.licdn.com/dms/image/C5603AQHdO--ED2K5kA/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=ToxSdsrcHMkDC8OMrdBEMSyMtkSPdxk4tlcsOzEgp-I', 'www.linkedin.com/in/timjohnson78/', 1, FALSE, FALSE, 1),
    ('Justin Oakes', 'iOS Developer at Loves Travel Stops', 'iOS @ Loves Travel Stops', 'Oklahoma City, Oklahoma', '2017-Present', 'CEO @ Oklasoft', 'CEO', '2016-Present', 'iOS Development', 'OS X', 'Cocoa Touch', 'Dev Mountain', 'iOS Development', '2015-2015', 'https://media.licdn.com/dms/image/C4E03AQGW91CBRQxhlg/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=5sjLuTjSvZqaXfNlS1_v6HZh6EgY_t9xjmXf7hQFjF0', 'www.linkedin.com/in/justin-oakes-49a37292/', 1, FALSE, FALSE, 1),
    ('Cahlan Sharp', 'Highly versatile and adaptive leader, technologist, entrepreneur and engineer with expertise in conception, creation, iteration, and deployment of technology platforms and tools.', 'Founder, CEO @ DevMountain', 'DevMountain is a quickly growing top code school in the country. With dozens of five star reviews, affordable student housing provided, and over 500 students graduating annually, DevMountain continues to make an impact in students lives by providing them modern skills for the tech economy.', '2013-Present', 'Product Engineer @ Scan', 'Scan is a barcode/QR code scanning application available on Apple, Microsoft, and Google mobile app stores.', '2013-2014', 'Web Development', 'iOS Development', 'HTML 5', 'MS Psychology and Technology', 'Brigham Young University', '2007-2010', 'https://media.licdn.com/dms/image/C4E03AQFtwfMN25n7vw/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=CoTQZ2EIIfrRWBvs2FYNQwdib0vYftKiPBBPJtg7JgU', 'www.linkedin.com/in/cahlan/', 3, FALSE, FALSE, 1),
    ('Mark Mclver', 'Resident Engineer at DevMountain', 'Resident Engineer @ DevMountain', 'Provo, UT', '2017-Present', 'Developer @ Objective', 'Greater Salt Lake City Area', '2016-2017', 'CSS', 'HTML', 'JavaScript', 'MEAN Stack Web Dev', 'DevMountain', '2015-2015', 'https://media.licdn.com/dms/image/C5603AQHqBy1pMoGP4w/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=Xw1JOYXWz0USbiM_NnDYnNcvdFkmf2eQGcm3nR8f5xs', 'www.linkedin.com/in/markmciver1983/', 2, FALSE, FALSE, 1),
    ('Luis Curvelo', 'Retail Partner Integration Specialist by day, Freelance Web Developer by night.', 'Retail Partner Integration Specialist @ Jet.com', 'Identify and troubleshoot 3rd party marketplace integration issues.', '2016-Present', 'Member Services Associate @ Jet.com', 'Provided quick resolution and ability to resolve problems on the first contact and avoid escalations.', '2016-2016', 'CSS', 'Underscore.js', 'React', 'Full Stack Developer', 'DevMountain', '2017-2017', 'https://media.licdn.com/dms/image/C5603AQGLmgCTf6ZyTQ/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=LkmnIq0eBJ0EUtMl5vPTvm7OjzQ_ti3wKDyhI1wPpMs', 'www.linkedin.com/in/luis-curvelo-45b842149/', 2, FALSE, FALSE, 1),
    ('Christian Jensen', 'Analytical, diligent, and respectful. Always learning.', 'Jr. Web Developer @ Deluxe', 'Work with various programming languages, including PHP, HTML, CSS, and JavaScript, as well as other libraries and frameworks like Bootstrap and jQuery.', '2017-Present', 'GlasPac Software Tech @ AutoPoint', 'Responded to incoming e-mails, chats and calls regarding GlasPac LX, a POS software for glass shops', '2016-2017', 'JavaScript', 'HTML', 'CSS', 'Computer Science', 'DevMountain', '2015-2015', 'https://www.linkedin.com/in/cbejensen/detail/photo/', 'www.linkedin.com/in/cbejensen/', 2, FALSE, FALSE, 1),

    ('Austin Wright', 'I am a full-stack web developer with a passion for family, music, computers, technology, religion, and all things outdoors. I got into web development to be more immersed in the tech field where I can help create websites and applications to make life better for people around the world.', 'Full Stack Web Developer @ Dev Mountain', 'Redesigned and built Lahnas Chocolates website', '2017-2018', 'Full Stack Web Developer @ Dev Mountain', 'Served as a member of the group who designed and built Planappus.', '2017-2018', 'JavaScript', 'React.js', 'Node.js', 'AS General Studies', 'Salt Lake Community College', '2013-2018', 'https://media.licdn.com/dms/image/C4E03AQFqGpa_shoH6w/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=KkK5a3D7P03cdS3QqtO9pBM3adbsoQm8a7KylAjyaas', 'www.linkedin.com/in/in/theaustinwright/', 2, FALSE, FALSE, 1),
    ('Landon Johnson', 'Bright, talented and ambitious IT support technician with strong technical background, possessing self-discipline and the ability to work with minimum supervision.', 'Graphic Design Intern @ More Good Foundation', 'Orem, UT', '2017-2017', 'Computer Technician @ PcCareSupport', 'Perform inbound and outbound calls from existing and new clients.', '2013-2014', 'Graphic Design', 'Illustrator', 'Photoshop', 'Fullstack Javascript Development', 'DevMountain', '2017-2018', 'https://media.licdn.com/dms/image/C5603AQG3JSoqovpsjQ/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=UNxFDWSO4skDctfqK8fbIY_Tl2WaP5e-9h_wMhapQ1k', 'www.linkedin.com/in/landonwjohnson/', 2, FALSE, FALSE, 1),
    ('Greg Roberts', 'Front-end Web Developer', 'Web Developer @ BambooHR', 'Web Developer', '2015-Present', 'Front-end Web Developer @ InsideSales.com', 'Building responsive web pages, micro-sites, and web apps for the InsideSales.com marketing team.', '2013-2015', 'CSS', 'HTML 5', 'AngularJS', 'Web Development', 'Dev Mountain', '2014-2014', 'https://media.licdn.com/dms/image/C5603AQH3FpC-HgVq1A/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=RlqbwjdmqBAlYS3ZWbXIJjDHu2YAvr2l-VpGDAyGBHo', 'www.linkedin.com/in/gregorystephenroberts/', 2, FALSE, FALSE, 1),
    ('Samuel Skeen', 'I have a passion for programming, a veneration for web development and design. I can program anywhere JavaScript can run', 'Frontend Developer @ Red Pepper Software', 'Pleasant Grove, Utah', '2018-Present', 'After-hours Web Mentor @ Dev Mountain', 'Help students learn JavaScript, React, Node, and Postgres in a 16-week, intensive bootcamp course.', '2017-Present', 'JavaScript', 'CSS', 'JQuery', 'Web Development Certification', 'Dev Mountain', '2015-2015', 'https://media.licdn.com/dms/image/C5603AQEJ6I9Uvs8N3Q/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=cKwfO12yskv6eYlbyFzeSqquVYElOOX6VIEcT0oE75A', 'www.linkedin.com/in/cwadrupldijjit/', 2, FALSE, FALSE, 1),
    ('Paul Olsen', 'Fought multiple ventilation fires on a 500 foot US Naval Vessel. Obsessed with the intersection between people and technology. Chose not to climb Mt. Fuji.', 'Student Success Manager @ DevMountain', 'Enabling the next wave of Creators and Developers!', '2017-Present', 'Technical Sourcer/Recruiter @ Thumbtack', 'Sourcing Engineering candidates through LinkedIn, Github, Slack, Reddit, Search ', '2015-2017', 'SaaS', 'Android', 'iOS', 'Center for Information Dominance Unit', 'US Navy', '2008-2012', 'https://media.licdn.com/dms/image/C5603AQEVub1bk84TTA/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=3I-oU16izLsSa5eLgObAKuxTwsA53dWcC1OIBTYu4kU', 'www.linkedin.com/in/paulolsen1337/', 2, FALSE, FALSE, 1),
    ('Jon Myrick', 'In my years of professional software development, I have had extensive experience coding and working in teams where communication is essential to success. I know how to find answers and get the job done right the first time.', 'Full Stack Javascript Developer @ Vivint Solar', 'API (REST,SOAP) Front Javascript(React), Backend Javascript (Node.js), MongoDB, AWS, Unit Testing', '2017-Present', 'Instructor @ Dev Mountain', 'Instructor', '2016-Present', 'JavaScript', 'Node.js', 'React.js', 'BA Computer Science', 'Brigham Young University', '2015', 'https://media.licdn.com/dms/image/C5103AQHJmsWsjdcT1Q/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=ikv34rv8qn9Lv4LFhhyLxDGenLg_Cwd4vGGXT13soas', 'www.linkedin.com/in/jonmyrick/', 2, FALSE, FALSE, 1),
    ('Joshua Smith', 'I love programming, solving problems, and creating cool stuff. Im crazy about react and javascript (ES6), but thats not all I can do. I currently work two jobs with two different stacks.', 'Software Developer @ Alder Holdings', 'We build and maintain alders customer management and sales tracking software.', '2017-Present', 'Software Instructor @ Dev Mountain', 'At DevMountain we teach by doing. We build projects together, we discuss and demonstrate programing concepts together, and we show practical real world applications for those concepts.', '2017-Present', 'Web Development', 'Front-end Development', 'Node.js', 'BS Sports and Exercise', 'Utah Valley University', '2016-2020', 'https://media.licdn.com/dms/image/C4E03AQHZJmUdm-_-CQ/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=_RQVJzKMF-ZhVmqzamp1M9ouVe2y-K7S-TBFlHsDYoE', 'www.linkedin.com/in/joshua-smith-66a90888/', 2, FALSE, FALSE, 1),
    ('Brian Rogers', 'Strong ability to be versatile with skillset that includes both PHP development and DevOps experience - Highly motivated in both personal and professional endeavors', 'Freelance Software Consultant @ Lucky Dev Shop', 'I am a full-time freelance software developer and consultant. I can assist you, or a team at your company, with a myriad of tasks.', '2017-Present', 'Senior Director of Technology @ ControlPad', 'I was the principle architect for the core product offered, responsible for deciding project guidelines, workflow, and standardization for a team of front-end and back-end developers.', '2015-2017', 'PHP', 'JavaScript', 'Web dev', 'BS Computer Science', 'Southern Utah University', '2009-2011', 'https://media.licdn.com/dms/image/C5603AQE-eWN8HIZhEw/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=P4QNX39FUC_x63Gzs58i7SA1ive5HVNJbwAOCEGZswA', 'www.linkedin.com/in/captbrogers/', 2, FALSE, FALSE, 1),
    ('Timothy Johnson', 'Senior Software Engineer at Silicon Mountain Technologies', 'Sr. Software Engineer @ Silicon Mountain Technologies', 'Westminster, Colorado', '2013-Present', 'Senior Web Developer @ Summit Web Dev', 'Thornton, Colorado', '2010-Present', 'E-commerce', 'Web Development', 'CMS', 'BS Computer Science', 'Colorado State University', '1999-2003', 'https://media.licdn.com/dms/image/C5603AQHdO--ED2K5kA/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=ToxSdsrcHMkDC8OMrdBEMSyMtkSPdxk4tlcsOzEgp-I', 'www.linkedin.com/in/timjohnson78/', 1, FALSE, FALSE, 1),

    ('Paul Olsen', 'Fought multiple ventilation fires on a 500 foot US Naval Vessel. Obsessed with the intersection between people and technology. Chose not to climb Mt. Fuji.', 'Student Success Manager @ DevMountain', 'Enabling the next wave of Creators and Developers!', '2017-Present', 'Technical Sourcer/Recruiter @ Thumbtack', 'Sourcing Engineering candidates through LinkedIn, Github, Slack, Reddit, Search ', '2015-2017', 'SaaS', 'Android', 'iOS', 'Center for Information Dominance Unit', 'US Navy', '2008-2012', 'https://media.licdn.com/dms/image/C5603AQEVub1bk84TTA/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=3I-oU16izLsSa5eLgObAKuxTwsA53dWcC1OIBTYu4kU', 'www.linkedin.com/in/paulolsen1337/', 3, FALSE, FALSE, 1),
    ('Jon Myrick', 'In my years of professional software development, I have had extensive experience coding and working in teams where communication is essential to success. I know how to find answers and get the job done right the first time.', 'Full Stack Javascript Developer @ Vivint Solar', 'API (REST,SOAP) Front Javascript(React), Backend Javascript (Node.js), MongoDB, AWS, Unit Testing', '2017-Present', 'Instructor @ Dev Mountain', 'Instructor', '2016-Present', 'JavaScript', 'Node.js', 'React.js', 'BA Computer Science', 'Brigham Young University', '2015', 'https://media.licdn.com/dms/image/C5103AQHJmsWsjdcT1Q/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=ikv34rv8qn9Lv4LFhhyLxDGenLg_Cwd4vGGXT13soas', 'www.linkedin.com/in/jonmyrick/', 3, FALSE, FALSE, 1),
    ('Joshua Smith', 'I love programming, solving problems, and creating cool stuff. Im crazy about react and javascript (ES6), but thats not all I can do. I currently work two jobs with two different stacks.', 'Software Developer @ Alder Holdings', 'We build and maintain alders customer management and sales tracking software.', '2017-Present', 'Software Instructor @ Dev Mountain', 'At DevMountain we teach by doing. We build projects together, we discuss and demonstrate programing concepts together, and we show practical real world applications for those concepts.', '2017-Present', 'Web Development', 'Front-end Development', 'Node.js', 'BS Sports and Exercise', 'Utah Valley University', '2016-2020', 'https://media.licdn.com/dms/image/C4E03AQHZJmUdm-_-CQ/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=_RQVJzKMF-ZhVmqzamp1M9ouVe2y-K7S-TBFlHsDYoE', 'www.linkedin.com/in/joshua-smith-66a90888/', 3, FALSE, FALSE, 1),
    ('Brian Rogers', 'Strong ability to be versatile with skillset that includes both PHP development and DevOps experience - Highly motivated in both personal and professional endeavors', 'Freelance Software Consultant @ Lucky Dev Shop', 'I am a full-time freelance software developer and consultant. I can assist you, or a team at your company, with a myriad of tasks.', '2017-Present', 'Senior Director of Technology @ ControlPad', 'I was the principle architect for the core product offered, responsible for deciding project guidelines, workflow, and standardization for a team of front-end and back-end developers.', '2015-2017', 'PHP', 'JavaScript', 'Web dev', 'BS Computer Science', 'Southern Utah University', '2009-2011', 'https://media.licdn.com/dms/image/C5603AQE-eWN8HIZhEw/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=P4QNX39FUC_x63Gzs58i7SA1ive5HVNJbwAOCEGZswA', 'www.linkedin.com/in/captbrogers/', 3, FALSE, FALSE, 1),
    ('Timothy Johnson', 'Senior Software Engineer at Silicon Mountain Technologies', 'Sr. Software Engineer @ Silicon Mountain Technologies', 'Westminster, Colorado', '2013-Present', 'Senior Web Developer @ Summit Web Dev', 'Thornton, Colorado', '2010-Present', 'E-commerce', 'Web Development', 'CMS', 'BS Computer Science', 'Colorado State University', '1999-2003', 'https://media.licdn.com/dms/image/C5603AQHdO--ED2K5kA/profile-displayphoto-shrink_800_800/0?e=1530748800&v=beta&t=ToxSdsrcHMkDC8OMrdBEMSyMtkSPdxk4tlcsOzEgp-I', 'www.linkedin.com/in/timjohnson78/', 1, FALSE, FALSE, 1),

    ('Chad Zuniga', 'Aspiring full stack developer currently recruiting Software Engineers for Thumbtack', 'Sr. Techincal Sourcer @ Thumbtack', 'Recruiting Software Engineers', '2015-Present', 'Student Developer @ Dev Mountain', 'Student Developer', '2017-2018', 'Node.js', 'PostgreSQL', 'React', 'BA Business Management', 'Kansas Welseyan University', '2011-2013', 'https://www.goaltos.com/wp-content/uploads/sites/4559/2018/01/avatar-1577909_960_720.png', 'www.linkedin.com/in/chad-zuniga-425735bb/', 4, FALSE, FALSE, 1),
    ('Chad Zuniga', 'Aspiring full stack developer currently recruiting Software Engineers for Thumbtack', 'Sr. Techincal Sourcer @ Thumbtack', 'Recruiting Software Engineers', '2015-Present', 'Student Developer @ Dev Mountain', 'Student Developer', '2017-2018', 'Node.js', 'PostgreSQL', 'React', 'BA Business Management', 'Kansas Welseyan University', '2011-2013', 'https://www.goaltos.com/wp-content/uploads/sites/4559/2018/01/avatar-1577909_960_720.png', 'www.linkedin.com/in/chad-zuniga-425735bb/', 4, FALSE, FALSE, 1),
    ('Chad Zuniga', 'Aspiring full stack developer currently recruiting Software Engineers for Thumbtack', 'Sr. Techincal Sourcer @ Thumbtack', 'Recruiting Software Engineers', '2015-Present', 'Student Developer @ Dev Mountain', 'Student Developer', '2017-2018', 'Node.js', 'PostgreSQL', 'React', 'BA Business Management', 'Kansas Welseyan University', '2011-2013', 'https://www.goaltos.com/wp-content/uploads/sites/4559/2018/01/avatar-1577909_960_720.png', 'www.linkedin.com/in/chad-zuniga-425735bb/', 4, FALSE, FALSE, 1),
    ('Chad Zuniga', 'Aspiring full stack developer currently recruiting Software Engineers for Thumbtack', 'Sr. Techincal Sourcer @ Thumbtack', 'Recruiting Software Engineers', '2015-Present', 'Student Developer @ Dev Mountain', 'Student Developer', '2017-2018', 'Node.js', 'PostgreSQL', 'React', 'BA Business Management', 'Kansas Welseyan University', '2011-2013', 'https://www.goaltos.com/wp-content/uploads/sites/4559/2018/01/avatar-1577909_960_720.png', 'www.linkedin.com/in/chad-zuniga-425735bb/', 4, FALSE, FALSE, 1),
    ('Chad Zuniga', 'Aspiring full stack developer currently recruiting Software Engineers for Thumbtack', 'Sr. Techincal Sourcer @ Thumbtack', 'Recruiting Software Engineers', '2015-Present', 'Student Developer @ Dev Mountain', 'Student Developer', '2017-2018', 'Node.js', 'PostgreSQL', 'React', 'BA Business Management', 'Kansas Welseyan University', '2011-2013', 'https://www.goaltos.com/wp-content/uploads/sites/4559/2018/01/avatar-1577909_960_720.png', 'www.linkedin.com/in/chad-zuniga-425735bb/', 4, FALSE, FALSE, 1),

    ('Chad Zuniga', 'Aspiring full stack developer currently recruiting Software Engineers for Thumbtack', 'Sr. Techincal Sourcer @ Thumbtack', 'Recruiting Software Engineers', '2015-Present', 'Student Developer @ Dev Mountain', 'Student Developer', '2017-2018', 'Node.js', 'PostgreSQL', 'React', 'BA Business Management', 'Kansas Welseyan University', '2011-2013', 'https://www.goaltos.com/wp-content/uploads/sites/4559/2018/01/avatar-1577909_960_720.png', 'www.linkedin.com/in/chad-zuniga-425735bb/', 5, FALSE, FALSE, 1),
    ('Chad Zuniga', 'Aspiring full stack developer currently recruiting Software Engineers for Thumbtack', 'Sr. Techincal Sourcer @ Thumbtack', 'Recruiting Software Engineers', '2015-Present', 'Student Developer @ Dev Mountain', 'Student Developer', '2017-2018', 'Node.js', 'PostgreSQL', 'React', 'BA Business Management', 'Kansas Welseyan University', '2011-2013', 'https://www.goaltos.com/wp-content/uploads/sites/4559/2018/01/avatar-1577909_960_720.png', 'www.linkedin.com/in/chad-zuniga-425735bb/', 5, FALSE, FALSE, 1),
    ('Chad Zuniga', 'Aspiring full stack developer currently recruiting Software Engineers for Thumbtack', 'Sr. Techincal Sourcer @ Thumbtack', 'Recruiting Software Engineers', '2015-Present', 'Student Developer @ Dev Mountain', 'Student Developer', '2017-2018', 'Node.js', 'PostgreSQL', 'React', 'BA Business Management', 'Kansas Welseyan University', '2011-2013', 'https://www.goaltos.com/wp-content/uploads/sites/4559/2018/01/avatar-1577909_960_720.png', 'www.linkedin.com/in/chad-zuniga-425735bb/', 5, FALSE, FALSE, 1),
    ('Chad Zuniga', 'Aspiring full stack developer currently recruiting Software Engineers for Thumbtack', 'Sr. Techincal Sourcer @ Thumbtack', 'Recruiting Software Engineers', '2015-Present', 'Student Developer @ Dev Mountain', 'Student Developer', '2017-2018', 'Node.js', 'PostgreSQL', 'React', 'BA Business Management', 'Kansas Welseyan University', '2011-2013', 'https://www.goaltos.com/wp-content/uploads/sites/4559/2018/01/avatar-1577909_960_720.png', 'www.linkedin.com/in/chad-zuniga-425735bb/', 5, FALSE, FALSE, 1),
    ('Chad Zuniga', 'Aspiring full stack developer currently recruiting Software Engineers for Thumbtack', 'Sr. Techincal Sourcer @ Thumbtack', 'Recruiting Software Engineers', '2015-Present', 'Student Developer @ Dev Mountain', 'Student Developer', '2017-2018', 'Node.js', 'PostgreSQL', 'React', 'BA Business Management', 'Kansas Welseyan University', '2011-2013', 'https://www.goaltos.com/wp-content/uploads/sites/4559/2018/01/avatar-1577909_960_720.png', 'www.linkedin.com/in/chad-zuniga-425735bb/', 5, FALSE, FALSE, 1)
;